exec-once = waybar 
exec-once = swww-daemon 
exec-once = swaync 
exec-once = hypridle 
exec-once = fcitx5
exec-once = ~/.local/scripts/watch_images.sh
exec-once = xrdb -merge ~/.Xresources
exec-once = systemctl --user start hyprpolkitagent
