render:cm_sdr_eotf = 2
source = /home/$USER/.cache/wal/colors-hyprland.conf

################
### MONITORS ###
################

monitor=eDP-1,1920x1080@60,auto,1
monitor=HDMI-A-2,1920x1080@60,auto,1

###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = kitty bash -ci yazi
$menu = wofi --show drun -n
$browser = zen-browser

#################
### AUTOSTART ###
#################

source = ~/.config/hypr/autostart.conf

# Workspace rules
workspace = special:scratchpad, on-created-empty:$terminal
workspace = special:filemanager, on-created-empty:$fileManager

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE, 24
env = XCURSOR_THEME, phinger-cursors-light
env = QT_QPA_PLATFORMTHEME, qt6ct

#####################
### LOOK AND FEEL ###
#####################

general { 
    gaps_in = 2
    gaps_out = 7
    border_size = 2
    resize_on_border = false 
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 12

    # Change transparency of focused and unfocused windows
    active_opacity = 0.8
    inactive_opacity = 0.8

    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 10
        passes = 3
        vibrancy = 0.1696
    }
}

animations {

    enabled = true

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 3, myBezier
    animation = windowsOut, 1, 3, default, popin 85%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 3, default
    animation = workspaces, 1, 3, default, slidefade 4%
    animation = specialWorkspace, 1, 3, default, fade
}

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
	special_scale_factor = 0.75
    force_split = 2
}

master {
    new_status = master
}

misc { 
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

#############
### INPUT ###
#############

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    sensitivity = 0
    repeat_delay = 350
    repeat_rate = 35

    touchpad {
        natural_scroll = true
    }
}

cursor {
    no_warps = 1
    inactive_timeout = 1
    hide_on_key_press = true
}

gestures {
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

####################
### KEYBINDINGSS ###
####################

binds {
    movefocus_cycles_fullscreen = 0
}

$mainMod = SUPER

source = ~/.config/hypr/keybinds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################
# Custom Window Rules

windowrule {
  name = windowrule-1
  opaque = on
  match:class = vlc|mpv|feh|zen|Nsxiv|org.pwmt.zathura|wine
}

windowrule {
  name = windowrule-2
  animation = slide 1
  match:class = zen
}

windowrule {
  name = windowrule-4
  float = on
  match:class = org.kde.kdeconnect.daemon|feh
}

windowrule {
  name = windowrule-5
  move = (1494) (913)
  match:class = org.kde.kdeconnect.daemon
}


# Layer Rules
layerrule {
  name = layerrule-1
  blur = on
  ignore_alpha = 0.5
  match:namespace = waybar
}

layerrule {
  name = layerrule-2
  blur = on
  ignore_alpha = 0.5
  match:namespace = swaync-control-center
}

layerrule {
  name = layerrule-3
  blur = on
  ignore_alpha = 0.5
  match:namespace = swaync-notification-window
}

layerrule {
  name = layerrule-4
  no_anim = on
  match:namespace = selection
}
