--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/umair/Pictures/Wallpapers/Wallpaper-40.jpg"

-- Special
background="#0A060B"
foreground="#c1c0c2"
cursor="#c1c0c2"

-- Colors
color0="#0A060B"
color1="#78493c"
color2="#99533f"
color3="#786b54"
color4="#a66c54"
color5="#437064"
color6="#a7816f"
color7="#918995"
color8="#615567"
color9="#A16250"
color10="#CC6F54"
color11="#A18F70"
color12="#DE9070"
color13="#5A9686"
color14="#DFAD94"
color15="#c1c0c2"
