[colors.primary]
background = "#0D080C"
foreground = "#c2c1c2"

[colors.cursor]
text = "#0D080C"
cursor = "#c2c1c2"

[colors.vi_mode_cursor]
text = "#0D080C"
cursor = "#c2c1c2"

[colors.search.matches]
foreground = "#0D080C"
background = "#c2c1c2"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#695569"
background = "#968a92"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0D080C"
red = "#4b3b4b"
green = "#6b2751"
yellow = "#763a51"
blue = "#5b3565"
magenta = "#813975"
cyan = "#843675"
white = "#968a92"

[colors.bright]
black = "#695569"
red = "#654F64"
green = "#8F346D"
yellow = "#9E4E6C"
blue = "#7A4787"
magenta = "#AC4C9D"
cyan = "#B0489D"
white = "#c2c1c2"

[colors.dim]
black = "#c2c1c2"
red = "#654F64"
green = "#AC4C9D"
yellow = "#9E4E6C"
blue = "#7A4787"
magenta = "#8F346D"
cyan = "#B0489D"
white = "#695569"

