[colors.primary]
background = "#0c061f"
foreground = "#c2c0c7"

[colors.cursor]
text = "#0c061f"
cursor = "#c2c0c7"

[colors.vi_mode_cursor]
text = "#0c061f"
cursor = "#c2c0c7"

[colors.search.matches]
foreground = "#0c061f"
background = "#c2c0c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5f5a6f"
background = "#918e99"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0c061f"
red = "#3c293e"
green = "#54273e"
yellow = "#423549"
blue = "#77263f"
magenta = "#a4243d"
cyan = "#763243"
white = "#918e99"

[colors.bright]
black = "#5f5a6f"
red = "#503753"
green = "#713553"
yellow = "#594762"
blue = "#9F3355"
magenta = "#DB3052"
cyan = "#9E435A"
white = "#c2c0c7"

[colors.dim]
black = "#c2c0c7"
red = "#503753"
green = "#DB3052"
yellow = "#594762"
blue = "#9F3355"
magenta = "#713553"
cyan = "#9E435A"
white = "#5f5a6f"

