# Shell variables
# Generated by 'wal'
wallpaper="/home/umair/Pictures/Wallpapers/Wallpaper-43.jpg"

# Special
background='#091112'
foreground='#c1c3c3'
cursor='#c1c3c3'

# Colors
color0='#091112'
color1='#457857'
color2='#54815b'
color3='#6d845a'
color4='#598660'
color5='#678c62'
color6='#7d9866'
color7='#8c9497'
color8='#576b6b'
color9='#5CA074'
color10='#71AC7A'
color11='#92B178'
color12='#77B381'
color13='#8ABB83'
color14='#A7CB89'
color15='#c1c3c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
