--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/umair/Pictures/Wallpapers/Wallpaper-7.jpg"

-- Special
background="#0D080C"
foreground="#c2c1c2"
cursor="#c2c1c2"

-- Colors
color0="#0D080C"
color1="#4b3b4b"
color2="#6b2751"
color3="#763a51"
color4="#5b3565"
color5="#813975"
color6="#843675"
color7="#968a92"
color8="#695569"
color9="#654F64"
color10="#8F346D"
color11="#9E4E6C"
color12="#7A4787"
color13="#AC4C9D"
color14="#B0489D"
color15="#c2c1c2"
