--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/umair/Pictures/Wallpapers/Wallpaper-32.jpg"

-- Special
background="#0B131D"
foreground="#bfd2dd"
cursor="#bfd2dd"

-- Colors
color0="#0B131D"
color1="#447799"
color2="#5C90B1"
color3="#76A6C4"
color4="#F8B094"
color5="#FCD2B1"
color6="#FBDDB3"
color7="#bfd2dd"
color8="#85939a"
color9="#447799"
color10="#5C90B1"
color11="#76A6C4"
color12="#F8B094"
color13="#FCD2B1"
color14="#FBDDB3"
color15="#bfd2dd"
