--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/umair/Pictures/Wallpapers/Wallpaper-43.jpg"

-- Special
background="#091112"
foreground="#c1c3c3"
cursor="#c1c3c3"

-- Colors
color0="#091112"
color1="#457857"
color2="#54815b"
color3="#6d845a"
color4="#598660"
color5="#678c62"
color6="#7d9866"
color7="#8c9497"
color8="#576b6b"
color9="#5CA074"
color10="#71AC7A"
color11="#92B178"
color12="#77B381"
color13="#8ABB83"
color14="#A7CB89"
color15="#c1c3c3"
