# Shell variables
# Generated by 'wal'
wallpaper="/home/umair/Pictures/Wallpapers/Wallpaper-40.jpg"

# Special
background='#0A060B'
foreground='#c1c0c2'
cursor='#c1c0c2'

# Colors
color0='#0A060B'
color1='#78493c'
color2='#99533f'
color3='#786b54'
color4='#a66c54'
color5='#437064'
color6='#a7816f'
color7='#918995'
color8='#615567'
color9='#A16250'
color10='#CC6F54'
color11='#A18F70'
color12='#DE9070'
color13='#5A9686'
color14='#DFAD94'
color15='#c1c0c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
