[colors.primary]
background = "#091112"
foreground = "#c1c3c3"

[colors.cursor]
text = "#091112"
cursor = "#c1c3c3"

[colors.vi_mode_cursor]
text = "#091112"
cursor = "#c1c3c3"

[colors.search.matches]
foreground = "#091112"
background = "#c1c3c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#576b6b"
background = "#8c9497"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#091112"
red = "#457857"
green = "#54815b"
yellow = "#6d845a"
blue = "#598660"
magenta = "#678c62"
cyan = "#7d9866"
white = "#8c9497"

[colors.bright]
black = "#576b6b"
red = "#5CA074"
green = "#71AC7A"
yellow = "#92B178"
blue = "#77B381"
magenta = "#8ABB83"
cyan = "#A7CB89"
white = "#c1c3c3"

[colors.dim]
black = "#c1c3c3"
red = "#5CA074"
green = "#8ABB83"
yellow = "#92B178"
blue = "#77B381"
magenta = "#71AC7A"
cyan = "#A7CB89"
white = "#576b6b"

