# Shell variables
# Generated by 'wal'
wallpaper="/home/umair/Pictures/Wallpapers/Wallpaper-26.jpg"

# Special
background='#0c061f'
foreground='#c2c0c7'
cursor='#c2c0c7'

# Colors
color0='#0c061f'
color1='#3c293e'
color2='#54273e'
color3='#423549'
color4='#77263f'
color5='#a4243d'
color6='#763243'
color7='#918e99'
color8='#5f5a6f'
color9='#503753'
color10='#713553'
color11='#594762'
color12='#9F3355'
color13='#DB3052'
color14='#9E435A'
color15='#c2c0c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
